# ─── API Gateway ────────────────────────────────────────────────
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: ferreteria-psa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: gateway
          imagePullPolicy: Never
          ports:
            - containerPort: 8085
          env:
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: ms-config
                  key: CONFIG_URL
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE   # ← corregido (tenía un espacio)
              valueFrom:
                configMapKeyRef:
                  name: ms-config
                  key: EUREKA_URL
#          readinessProbe:
#            httpGet:
#              path: /actuator/health
#              port: 8080
#            initialDelaySeconds: 60
#            periodSeconds: 10
#            failureThreshold: 10
---
# Service tipo LoadBalancer para acceder desde localhost
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: ferreteria-psa
spec:
  selector:
    app: gateway
  type: LoadBalancer        # ← expone en localhost:8085
  ports:
    - port: 8085
      targetPort: 8085