server:
  port: 8761
  
spring:
  application:
    name: 261DSWG2SpringMSLogisticaDemo01Eureka

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/